CREATE OR REPLACE TRIGGER Set_review_date
 BEFORE INSERT
 ON REVIEW
 FOR EACH ROW
BEGIN
 :NEW.REVIEW_DATE := SYSDATE;
END;

CREATE OR REPLACE TRIGGER Set_bill_date
 BEFORE INSERT
 ON BILL
 FOR EACH ROW
BEGIN
 :NEW.BILL_DATE := SYSDATE;
END;